<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace d3yii2\d3codes\models\base;


/**
 * This is the base-model class for table "d3codes_code".
 *
 * @property integer $id
 * @property string $name
 *
 * @property \d3yii2\d3codes\models\D3codesCodeRecord[] $d3codesCodeRecords
 * @property string $aliasModel
 */
abstract class D3CodesCode extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName(): string
    {
        return 'd3codes_code';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            'tinyint Unsigned' => [['id'],'integer' ,'min' => 0 ,'max' => 255],
            [['name'], 'string', 'max' => 50]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Name',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getD3codesCodeRecords()
    {
        return $this->hasMany(\d3yii2\d3codes\models\D3codesCodeRecord::className(), ['code_id' => 'id'])->inverseOf('code');
    }

}
